name: SyncTimeUTC
author: Malory
version: 1.3.3.7
description: Syncs the time with NIST and formats to UTC
main: me.malory.plugin.SyncTimeUTC.SyncTimeUTC
commands:
  SyncTimeUTC:
    description: Gets time and sets/reset offset 
  st:
    description: Gets time and sets/reset offset 
  utc:
    description: Returns the current time in UTC 
permissions:
  synctimeutc.use:
    description: Give user access to use the SyncTimeUTC command
    default: OP